import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { createFFmpeg } from "@ffmpeg/ffmpeg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    // Use API path to avoid CORS issues when trying to load web worker
    const worker = new Worker(
      new URL("/api/worker-example", window.location.origin)
    );
    // Listen for worker replies
    worker.addEventListener("message", (msg) =>
      console.log(`Client received: ${msg.data}`)
    );

    // Test worker interface
    worker.postMessage("🐱Msg from Client");

    const ffmpeg = createFFmpeg({
      log: true,
      corePath: "https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js",
    });
    ffmpeg
      .load()
      .then((e) => console.log(`✅Loaded FFmpeg: ${ffmpeg.isLoaded()}`, ffmpeg))
      .catch((e) => console.log(`❌Failed to Load FFmpeg: ${e}`));
  }, []);

  return (
    <>
      <Head>
        <title>FFmpeg.wasm & workers example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>
      </main>
    </>
  );
}
